### PR TITLE
Updates to search page design

### LINKED ISSUE #64: Update search page styling
#### Designs and Mockups

Desktop: https://projects.invisionapp.com/d/#/console/18609637/447781241/preview
Mobile: coming soon

#### Acceptance Criteria:

- [ ] Less white space at top
- [ ] New header text 
- [ ] courses/resources tab style
- [ ] Style filter buttons and clear all link per https://projects.invisionapp.com/d/#/console/18609637/447781243/preview and  https://projects.invisionapp.com/d/#/console/18609637/447781242/preview
- [ ] Accessibility for forms (labels, etc.)
- [ ] update search box/button

#### Out of Scope

- Not going to do

### PR DESCRIPTION
**Pull request by noisecapella**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Tag @ferdi or @pdpinch for review
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Fixes #64 

#### What's this PR do?
Updates styling according to issue

#### How should this be manually tested?
Go to `/search` and select some facets. It should look like the mockup in the linked issue

#### Screenshots (if appropriate)
(ignore the HTML images, those are just placeholders)

Screenshot_2021-03-22 Screenshot

### CODE REVIEW

**Comment by noisecapella** [comment]
FYI, new mockup. However the only change I can spot compared to the mockup in the linked issue is that the results count is on the right

https://projects.invisionapp.com/d/#/console/18609637/447781243/preview

**Comment by aliceriot** [comment]
I'm not sure how exact we want to get, but the spacing of things generally looks closer on the mockups to me:

Screenshot from 2021-03-23 16-58-32

than it does on this brnach:

Screenshot from 2021-03-23 16-58-38

I think the main difference I see is the padding below the 'explore open courseware,' and I think the font-size on that element is a little smaller on the mocks

**Comment by noisecapella** [comment]
@aliceriot FYI, there's a new design so I'm going to incorporate those changes and your feedback https://projects.invisionapp.com/d/#/console/18609637/447781243/preview

**Comment by noisecapella** [comment]
@aliceriot should be ready for another look

**Review by aliceriot — APPROVED** [review]
lgtm!

**Pull request merged**
