### PR TITLE
round out homepage mobile display

### LINKED ISSUE #23: Home: mobile styling
Looks like we lost some of our responsive styling on https://ocw-www--ocw-next.netlify.app/

image

#### Designs and Mockups

InVision: https://projects.invisionapp.com/d/main?origin=v7#/console/18552410/437726301/preview?scrollOffset=0

#### Acceptance Criteria:

- [ ] header (hero image, search box, learn more box)
- [ ] give section
- [ ] testimonials

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?

closes #23 

#### What's this PR do?

this brings the mobile display on the homepage in line with the designs.

#### How should this be manually tested?

check out the mobile display and make sure it looks good!

#### Screenshots (if appropriate)

Screenshot from 2021-01-22 08-54-33
Screenshot from 2021-01-22 08-54-26
Screenshot from 2021-01-22 08-54-20

### CODE REVIEW

**Comment by noisecapella** [comment]
I'm seeing a couple issues: 
 - The carousel buttons aren't working for me for the testimonial section
 - The display looks a little strange at one of the `large` widths. If you hover over the testimonial it expands slightly, squeezing the other icons.
Screenshot from 2021-01-22 13-12-06

**Comment by aliceriot** [comment]
yeah...I wonder if we should also do a three-across carousel for some of the intermediate widths

@abdulkdawson do you have any thoughts? you can see how it works on the PR build, here: https://ocw-www-pr-39--ocw-next.netlify.app/

**Comment by abdulkdawson** [comment]
@aliceriot I like the idea of decreasing the number of cards down to three for smaller screens.

**Comment by aliceriot** [comment]
cool, sounds good - should we do a carousel at that width or just hide one of the testimonials? then we'd have a carousel which shows 3 initially and has another 'page' with 1

**Review by noisecapella — APPROVED** [review]
Looks great :+1:

**Pull request merged**
