### PR TITLE
home page style updates

### LINKED ISSUE #3: Design changes in the front page header
Implement the changes within the hero image part of the front page

#### Designs and Mockups

https://invis.io/S5ZPUVV9FBQ#/440396978_OCW_NexGen_Homepage_12-11-2020_V4_Ferdi-s_Idea

Screen Shot 2021-01-06 at 9 19 50 AM

#### Acceptance Criteria:

- [x] Changes in design / font / color and text
- [x] Explore button goes to the search page
- [x] "Coming soon" for links that dont have a destination yet

### PR DESCRIPTION
**Pull request by aliceriot**
#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Mobile width screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?

closes #3 

#### What's this PR do?

updates copy and styles for the home page to be in-line with some tweaks on the mockups.

#### How should this be manually tested?

check it out and make sure all looks as it should.

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

### CODE REVIEW

**Comment by aliceriot** [comment]
@abdulkdawson @Ferdi  I haven't finished everything, but I wanted to get feedback on the changes so far. Does this capture what we're going for?

Screenshot from 2021-01-07 13-56-15

**Comment by aliceriot** [comment]
Screenshot from 2021-01-08 16-04-55

updated, now ready for review

**Comment by pdpinch** [comment]
FYI, comparing this PR to [this report on the prod version](https://foo-software-lighthouse-reports.s3.amazonaws.com/report-1610373645084.html), it seems like performance and SEO are both dropping, which best practice and accessibility are (nearly) the same. 

image

(yes, we need an easier way to do this...)

**Comment by abdulkdawson** [comment]
@aliceriot It's looking good so far. The only thing that I can see at this point that is a real issue is the alignment. 

Screen Shot 2021-01-11 at 12 49 00 PM

The section circled in red should be center-aligned with the section on the right.

**Comment by aliceriot** [comment]
@abdulkdawson has some extra bottom-padding on the 'Unlocking...' div which was messing up the centering. I think it should be all set now:

Screenshot from 2021-01-11 13-24-10

**Comment by abdulkdawson** [comment]
@aliceriot this looks good. Thank you!

**Review by mbertrand — APPROVED** [review]
👍

**Pull request merged**
