### PR TITLE
add generic page layout

### PR DESCRIPTION
**Pull request by gumaerc**
#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
  - [x] Desktop screenshots
  - [x] Mobile width screenshots
  - [x] Tag @ferdi or @pdpinch for review

#### What are the relevant tickets?
Related to https://github.com/mitodl/ocw-www/issues/69

#### What's this PR do?
We are going to be adding a notification system to `ocw-www`.  This PR adds a layout and archetype that allows for the creation of generic "pages" to be used for one-off purposes like linking from these notifications.

#### How should this be manually tested?
 - In the `site` directory, run `hugo new pages/test.md`
 - Start the site and browse to http://localhost:3000/pages/test/, you should see a blank page with the text "Insert content here"
 - Make an edit to `site/content/pages/test.md` and save the file, ensure the content is updated at the link above

#### Screenshots (if appropriate)
image
image

### CODE REVIEW

**Review by mbertrand — COMMENTED** [review]
Works great.  One question - is the empty `.keep` file necessary?

**Comment by gumaerc** [comment]
@mbertrand It's not necessary for the pages type to work, but I think it's best to make sure the folder appears in source control so it's obvious that this is a type of content that the site supports.

**Review by mbertrand — APPROVED** [review]
👍

**Comment by abdulkdawson** [comment]
@gumaerc here is the link to the generic page design. [https://projects.invisionapp.com/d/#/console/18609637/448521637/preview](urlhttps://projects.invisionapp.com/d/#/console/18609637/448521637/preview)

**Pull request merged**
